version: '3.9'
services:
  ### MySQL Container
  mysql:
    container_name: mysql
    build:
      dockerfile: mysql.Dockerfile
    image: mysql/db:v1
    networks:
      test:
        ipv4_address: 10.5.0.4
    ports:
      - "3306:3306"

  ### APP Container
  app:
    container_name: app
    build:
      dockerfile: app.Dockerfile
    image: app/be:v1
    depends_on:
      - mysql
    command: bash -c "sleep 20"
    networks:
      test:
        ipv4_address: 10.5.0.5
    ports:
      - "8082:8082"

volumes:
  db:
networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1